# Generated by Django 4.2.7 on 2024-01-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_empolyees_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empolyees',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
