# Generated by Django 4.2.7 on 2024-03-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_image_empolyees_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyees',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
