# Generated by Django 4.2.7 on 2024-03-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_empolyees_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyees',
            name='contact',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
