# Generated by Django 4.2.7 on 2024-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_empolyees_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='empolyees',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
